### ISSUE TITLE
hops0.31.jar

### ISSUE THREAD

**Issue by npsonis** [rhuebler/HOPS#4]
Hi,
I get a server problem when running sudo ./Installation/install_hops.sh.
"
--2020-07-10 12:06:18--  https://raw.githubusercontent.com/rhuebler/HOPS/external/Resources/hops0.31.jar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.240.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.240.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-10 12:06:20 ERROR 404: Not Found.
"

Best,

npsonis

**Comment by rhuebler** [comment]
Yes that is probably because I updated hops and did not change the installation script.  So I can recommend using the bioconda install though, that should be working

**Comment by npsonis** [comment]
Hi again,

after:    conda install hops -c bioconda

I get the following:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.                                  failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Any thoughts?

P.S. I tend to avoid bioconda as conflicts appear all the time in my machine...

**Comment by npsonis** [comment]
Hi again,

I found out that the conda version of 4.8 was to blame. I downgraded back to the stable 4.6.11 to make it work.

However,  now it gives the following error:


PackagesNotFoundError: The following packages are not available from current channels:

  - hops -> openjdk=8.0.144

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by rhuebler** [comment]
HI,

can you maybe try to initialize a new environment in conda
conda create --name hops (I think is the command)
conda activate hops
conda install hops -c bioconda?

I think if you try to install it into an "empty" environment it is more likely to suceed

**Comment by npsonis** [comment]
Hi rhuebler,

thanks for the reply.

After your suggestion I get conflict with r-base, malt, python and java:

Package r-gridbase conflicts for:
hops -> r-gridbase
Package malt conflicts for:
hops -> malt
Package python conflicts for:
hops -> python
Package r-gridextra conflicts for:
hops -> r-gridextra
Package openjdk conflicts for:
hops -> openjdk=8.0.144
Package r-getopt conflicts for:
hops -> r-getopt
Package r-base conflicts for:
hops -> r-base[version='>=3.5']
Package r-jsonlite conflicts for:
hops -> r-jsonlite
Package r-doparallel conflicts for:
hops -> r-doparallel

**Comment by rhuebler** [comment]
So just tried on our system to install it with latest conda version into an empty environment and it worked. So at least it is not generally broken. I think the version should be 0.34-0. 
Maybe you can add the conda-forge and bioconda channel to your conda version (not sure they are standard channels)

**Comment by npsonis** [comment]
So I created a new environment hops2 and I installed all the dependencies listed with conda search hops --info:

hops 0.34 0
-----------
file name   : hops-0.34-0.tar.bz2
name        : hops
version     : 0.34
build       : 0
build number: 0
size        : 69.6 MB
license     : GPL >=3
subdir      : noarch
url         : https://conda.anaconda.org/bioconda/noarch/hops-0.34-0.tar.bz2
md5         : c69ec3af4146934d24b6c2fcd642da43
timestamp   : 2020-05-27 19:47:45 UTC
dependencies:
  - malt
  - openjdk 8.0.144.*
  - python
  - r-base >=3.5
  - r-doparallel
  - r-getopt
  - r-gridbase
  - r-gridextra
  - r-jsonlite

Again I got the message:

Found conflicts! Looking for incompatible packages.                                       failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

 and then it exits

I tried conda config --add channels bioconda 
(already there, it moved at the top of the list)

And then I tried conda config --add channels conda-forge

After conda install hops -c bioconda it succesfully installed HOPS!

Thanks for the help,

You can close the issue now.

Stay safe.
